In [371]:
import pandas as pd
#import matplotlib.pyplot as plt
#import plotly.express as px
#import seaborn as sns

df = pd.read_csv('diamonds.csv')
df.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31
2,3,0.23,Good,E,VS1,56.9,65.0,327,4.05,4.07,2.31
3,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63
4,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75

In [372]:
df.shape

(53940, 11)

In [373]:
df.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000,53940.000000
mean,26970.500000,0.797940,61.749405,57.457184,3932.799722,5.731157,5.734526,3.538734
std,15571.281097,0.474011,1.432621,2.234491,3989.439738,1.121761,1.142135,0.705699
min,1.000000,0.200000,43.000000,43.000000,326.000000,0.000000,0.000000,0.000000
25%,13485.750000,0.400000,61.000000,56.000000,950.000000,4.710000,4.720000,2.910000
50%,26970.500000,0.700000,61.800000,57.000000,2401.000000,5.700000,5.710000,3.530000
75%,40455.250000,1.040000,62.500000,59.000000,5324.250000,6.540000,6.540000,4.040000
max,53940.000000,5.010000,79.000000,95.000000,18823.000000,10.740000,58.900000,31.800000

In [374]:
#checking null values
df.isnull().sum()

Unnamed: 0    0
carat         0
cut           0
color         0
clarity       0
depth         0
table         0
price         0
x             0
y             0
z             0
dtype: int64

In [375]:
#checking duplicates
print(df.duplicated().sum())

0

In [376]:
outliers = pd.DataFrame()
for col in df.select_dtypes(include = ['number']).columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    #lower and upper bounds for outliers
    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR
    #Identifying outliers for each column
    col_outliers = df[(df[col]<lower_bound) | (df[col] > upper_bound)]
    #if there are any outliers, append them to the outliers DataFrame
    if not col_outliers.empty:
        outliers = pd.concat([outliers, col_outliers])
outliers.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8689 entries, 12246 to 51506
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  8689 non-null   int64
 1   carat       8689 non-null   float64
 2   cut         8689 non-null   object
 3   color       8689 non-null   object
 4   clarity     8689 non-null   object
 5   depth       8689 non-null   float64
 6   table       8689 non-null   float64
 7   price       8689 non-null   int64
 8   x           8689 non-null   float64
 9   y           8689 non-null   float64
 10  z           8689 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 814.6+ KB

In [377]:
#import warnings
#warnings.filterwarnings("ignore")
#plt.figure(figsize=(10,8))
#sns.pairplot(df, hue="cut", palette="mako")
#plt.show()

In [378]:
df_cleaned = df.drop(outliers.index)
df_cleaned = df_cleaned.reset_index(drop=True)
df_cleaned.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47524 entries, 0 to 47523
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  47524 non-null  int64
 1   carat       47524 non-null  float64
 2   cut         47524 non-null  object
 3   color       47524 non-null  object
 4   clarity     47524 non-null  object
 5   depth       47524 non-null  float64
 6   table       47524 non-null  float64
 7   price       47524 non-null  int64
 8   x           47524 non-null  float64
 9   y           47524 non-null  float64
 10  z           47524 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.0+ MB

In [379]:
df_cleaned.describe()

,Unnamed: 0,carat,depth,table,price,x,y,z
count,47524.000000,47524.000000,47524.000000,47524.000000,47524.000000,47524.000000,47524.000000,47524.000000
mean,27206.946722,0.708700,61.786512,57.260186,3109.662381,5.546656,5.551478,3.428376
std,15989.963383,0.371104,1.105911,2.021552,2749.696633,0.979906,0.973990,0.606158
min,1.000000,0.200000,58.800000,52.000000,326.000000,3.730000,3.680000,1.410000
25%,12890.750000,0.380000,61.100000,56.000000,890.000000,4.640000,4.650000,2.860000
50%,29051.500000,0.600000,61.900000,57.000000,2061.000000,5.440000,5.450000,3.360000
75%,41283.250000,1.010000,62.500000,59.000000,4636.250000,6.410000,6.410000,3.980000
max,53940.000000,2.000000,64.700000,63.500000,11883.000000,8.280000,8.270000,5.300000

In [380]:
df_cleaned.dtypes

Unnamed: 0      int64
carat         float64
cut            object
color          object
clarity        object
depth         float64
table         float64
price           int64
x             float64
y             float64
z             float64
dtype: object

In [381]:
df_cleaned['cut'].value_counts()

cut
Ideal        20340
Premium      12115
Very Good    10994
Good          3745
Fair           330
Name: count, dtype: int64

In [382]:
df_cleaned['color'].value_counts()

color
G    10081
E     8910
F     8466
H     7176
D     6195
I     4462
J     2234
Name: count, dtype: int64

In [383]:
df_cleaned['clarity'].value_counts()

clarity
SI1     11552
VS2     10928
SI2      7402
VS1      7373
VVS2     4683
VVS1     3463
IF       1650
I1        473
Name: count, dtype: int64

In [384]:
df_cleaned['cut'] = df_cleaned['cut'].astype('category')
df_cleaned['cut Encoded'] = df_cleaned['cut'].cat.codes
df_cleaned.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,cut Encoded
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,2
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,3
2,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3
3,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,1
4,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,4

In [385]:
#df_cleaned[['cut', 'cut Encoded']].drop_duplicates().sort_values('cut Encoded')

In [386]:
df_cleaned['color'] = df_cleaned['color'].astype('category')
df_cleaned['color Encoded'] = df_cleaned['color'].cat.codes
df_cleaned.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,cut Encoded,color Encoded
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,2,1
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,3,1
2,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3,5
3,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,1,6
4,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,4,6

In [387]:
#df_cleaned[['color', 'color Encoded']].drop_duplicates().sort_values('color Encoded')

In [388]:
df_cleaned['clarity'] = df_cleaned['clarity'].astype('category')
df_cleaned['clarity Encoded'] = df_cleaned['clarity'].cat.codes
df_cleaned.head()

,Unnamed: 0,carat,cut,color,clarity,depth,table,price,x,y,z,cut Encoded,color Encoded,clarity Encoded
0,1,0.23,Ideal,E,SI2,61.5,55.0,326,3.95,3.98,2.43,2,1,3
1,2,0.21,Premium,E,SI1,59.8,61.0,326,3.89,3.84,2.31,3,1,2
2,4,0.29,Premium,I,VS2,62.4,58.0,334,4.20,4.23,2.63,3,5,5
3,5,0.31,Good,J,SI2,63.3,58.0,335,4.34,4.35,2.75,1,6,3
4,6,0.24,Very Good,J,VVS2,62.8,57.0,336,3.94,3.96,2.48,4,6,7

In [389]:
#df_cleaned[['clarity', 'clarity Encoded']].drop_duplicates().sort_values('clarity Encoded')

In [390]:
df_final = df_cleaned.drop(['cut','color','clarity','depth','table','Unnamed: 0'],axis=1)
df_final.head()

   carat  price     x     y     z  cut Encoded  color Encoded  clarity Encoded
0   0.23    326  3.95  3.98  2.43            2              1                3
1   0.21    326  3.89  3.84  2.31            3              1                2
2   0.29    334  4.20  4.23  2.63            3              5                5
3   0.31    335  4.34  4.35  2.75            1              6                3
4   0.24    336  3.94  3.96  2.48            4              6                7

In [391]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 47524 entries, 0 to 47523
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   carat            47524 non-null  float64
 1   price            47524 non-null  int64
 2   x                47524 non-null  float64
 3   y                47524 non-null  float64
 4   z                47524 non-null  float64
 5   cut Encoded      47524 non-null  int8
 6   color Encoded    47524 non-null  int8
 7   clarity Encoded  47524 non-null  int8
dtypes: float64(4), int64(1), int8(3)
memory usage: 1.9 MB

In [392]:
import numpy as np
import pickle
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score

In [393]:
X = df_final.drop('price',axis=1)
Y = df_final['price']

In [394]:
x_train, x_test,y_train, y_test = train_test_split(X,Y,test_size = 0.2, random_state = 42)

In [395]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)
with open('scaler.pkl','wb') as f:
    pickle.dump(scaler,f)

In [396]:
reg = LinearRegression()
reg.fit(x_train, y_train)

LinearRegression()

In [397]:
y_pred = reg.predict(x_test)
r2 = r2_score(y_test,y_pred)
mae = mean_absolute_error(y_test,y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
y_pred, y_test

(array([2888.74828238, 9197.26101425, 4842.68690233, ..., 3217.21835736,
         955.65331084,  542.05769296], shape=(9505,)),
 45363     2396
 21856    11540
 9549      4779
 2875      3334
 1422      3005
          ...
 15719     6773
 23773      687
 45442     2400
 25684      747
 31640      969
 Name: price, Length: 9505, dtype: int64)

In [398]:
print(f"R²: {r2}")
print(f"MAE: {mae}")
print(f"RMSE: {rmse}")

R²: 0.8911418850180824
MAE: 605.2252482090025
RMSE: 901.740961972369

In [399]:
print(pd.DataFrame(zip(X.columns, reg.coef_)))
print(reg.intercept_)

                 0            1
0            carat  3980.967930
1                x -2163.470396
2                y  1922.364591
3                z -1048.737611
4      cut Encoded   -38.775521
5    color Encoded  -328.434897
6  clarity Encoded   374.290661
3118.893842552408

In [400]:
pickle.dump(reg,open('DModel.pkl', 'wb'))